harness-meta:
  apiKey: xxxxx
  accountId: vpCkHKsDSxK9_KYfjCTMKA
  orgId: QE_Team
  projectId: Quality_Assurence
harness-pipelines:
  - id: GitOpsSnapshotSanity_Clone2
    local-inputsets:
      - id: inp1
        inputsetVars:
          - name: agentId
            type: String
            value: ashinagent
          - name: agentName
            type: String
            value: ashinagent
          - name: priority
            type: String
            value: P0
          - name: BASE_URI
            type: String
            value: https://c0f4-2401-4900-8838-890b-8842-633a-3f48-8204.ngrok-free.app
          - name: account_id
            type: String
            value: kmpySmUISimoRrJL6NL73w
          - name: username
            type: String
            value: admin@harness.io
          - name: password
            type: String
            value: 306bde90805d6a98417c0ae0bc9b7c5b

harness-properties:
  ci:
    codebase:
      build:
        spec:
          branch: ashin/hackweek
        type: branch
